# Nome da aplicação
spring.application.name=FlawlessRead

# Configurações da base de dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/flawlessread?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=flawless_user
spring.datasource.password=2024
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
apileague.api.key=9c266edfd64e4c83841b147892d1b9b9
